### DISCUSSION TITLE
Wärmepumpe optimieren

### DISCUSSION THREAD

**Discussion by gRiMMi83** [basti242/homeassistant_lg_therma_v_modbus#13] [General]
Ich hab mich die letzten zwei Tage etwas beschäftigt wie man eine Wärmepumpe optimal einstellen sollte. Dabei spielt das Thema Taktung ne große Rolle, und wäre das erste Setting das ich anpassen möchte.

hier ein Video das es gut beschreibt. https://youtu.be/uXW7nseeBEk?si=XyIxZOu9HA8OqPs5

habt ihr bei euch mal beobachtet wie eure WP Taktet?

![image](https://github.com/user-attachments/assets/c04e0c56-e53e-42ef-a67a-3a406a6b8e7e)

Bei mir läuft sie aktuell 18-22 Minuten und macht dann 14-15 Min Pause.

Ich würde gerne daher wie in dem Video erwähnt die Einstellung für Gradminuten ausprobieren, weis jemand wo und wie man die machen kann? Über Modbus? Wenn ja könnte man diese dann auch entsprechend der Außentemperatur über eine automatisation anpassen, um so effizient wie möglich zu sein. 
ähnlich wie wohl LG das über seinen AI Modus macht nur bisschen besser.

**Comment by fposch84** [comment]
Hallo, ich habe das gleiche Problem gehabt. Dank dieser tollen Lösung hier konnte ich die LG Therma V R32 per Modbus an Homeassistant koppeln. Beim anfahren des Kompressors erhöhe ich nun die Sollvorlauftempertur so weit, dass ich beim typischen 15 Min. anfahren nicht über die Hysterese komme. Danach gehe ich alle 2 Minuten mit dem Sollwert 1 Grad runter bis ich auf dem Zielwert bin (z.B. 30 Grad). Klappt 1A und vielen Dank nochmal an alle hier!

**Reply by gRiMMi83** [reply]
Hi @fposch84,
bin leider n totaler noob was das angeht, kannst du mir zeigen wie du das gelöst hast, oder ist das schon Bestandteil von Bastis script?

**Reply by basti242** [reply]
Würde mich auch interessieren.

**Comment by fposch84** [comment]
Anbei auch nochmal die Einstellungen des Waveshare RS232/485 Gateways, angebunden problemlos per WiFi:
![image](https://github.com/user-attachments/assets/8b2229c2-c5f8-4df8-ac55-fddb9a1c3910)
![image](https://github.com/user-attachments/assets/1c0db79f-80a1-4d01-b0c6-55b5ba2a1ddb)
![image](https://github.com/user-attachments/assets/3ac58164-23ad-4312-be9d-66b076776bc1)
![image](https://github.com/user-attachments/assets/530813c9-121c-468b-ae24-ab27fb93e7b4)

**Reply by dbawos-git** [reply]
Hallo fposch84, versuche auch gerade meine LG in HA einzubinden und bin in Netzwerkdingen noch nicht so bewandert. Die Serveradresse (in Deinem Screenshot 2 mal 192.168.1.77) ist bei mir vorbelegt mit 10.10.100.100 und 10.10.10.100 wenn ich das Gateway über den Accesspoint öffne. Muss ich das durch meine Heimnetzadresse oder die IP-Adresse meine HAGreen ersetzen?

**Comment by isarrider** [comment]
@gRiMMi83 hast du was für uns?

**Reply by gRiMMi83** [reply]
was meinst du?

**Comment by isarrider** [comment]
Sorry, ich meinte @fposch84, ob er seine Lösung teilt (das yaml)

**Comment by basti242** [comment]
sollte ungefähr sowas sein...

```yaml
alias: Takten reduzieren
description: >-
  Reduziert Takten der Wärmepumpe durch Erhöhung und schrittweises Absenkung der
  Heizkurvenverschiebung
triggers:
  - entity_id: binary_sensor.hp_compressor_status
    from: "off"
    to: "on"
    trigger: state
    alias: Wenn der Kompressor startet
  - trigger: state
    entity_id:
      - binary_sensor.hp_dhw_heating_status
    from:
      - "on"
    to:
      - "off"
    alias: Wenn Wassererwärmung ausgeschaltet wird.
conditions:
  - condition: state
    entity_id: binary_sensor.hp_dhw_heating_status
    state:
      - "off"
    alias: Warmwasserbereitung ist ausgeschaltet.
actions:
  - alias: Heizkurve initial um Wert x erhöhen
    target:
      entity_id:
        - input_number.hp_shift_value_in_auto_mode_circuit1
        - input_number.hp_shift_value_in_auto_mode_circuit2
    data:
      value: 5
    action: input_number.set_value
  - alias: Schrittweise Reduzierung im x-Minuten-Takt
    repeat:
      count: 5
      sequence:
        - delay:
            hours: 0
            minutes: 5
            seconds: 0
            milliseconds: 0
        - target:
            entity_id:
              - input_number.hp_shift_value_in_auto_mode_circuit1
              - input_number.hp_shift_value_in_auto_mode_circuit2
          action: input_number.decrement
          data: {}
mode: restart

```
