### DISCUSSION TITLE
Steuerung der LG Therma V

### DISCUSSION THREAD

**Discussion by TomHeckl** [basti242/homeassistant_lg_therma_v_modbus#24] [Q&A]
Hi, die Integration klappt nun bei mir und es werden Werte ausgelesen.
Wie kann ich nun die Anlage steuern?
Ich würde gern eine einfache Automatisierung aufbauen, wie sie am Display der WP auch möglich. Bspw. reduziere die Temperatur des Kreislaufs 1 in der Nacht um -3 Grad.
Kann mich hier jemand unterstützen?
VG
Tom

**Comment by basti242** [comment]
Hier hast du ein Beispiel für eine Automation.

```yaml
alias: Vorlauftemperatur Wärmepumpe nach Strompreis
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.most_expensive_hours_heatpump
    id: Teuerste Stunden Wärmepumpe "True"
    to: "on"
  - trigger: state
    entity_id:
      - binary_sensor.most_expensive_hours_heatpump
    id: Teuerste Stunden Wärmepumpe "False"
    to: "off"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Teuerste Stunden Wärmepumpe "True"
        sequence:
          - action: input_number.min
            metadata: {}
            data: {}
            target:
              entity_id: input_number.hp_shift_value_in_auto_mode_circuit2
        alias: Vorlauftemperatur reduzieren wenn Strom teuer
      - conditions:
          - condition: trigger
            id:
              - Teuerste Stunden Wärmepumpe "False"
        sequence:
          - action: input_number.set_value
            metadata: {}
            data:
              value: 0
            target:
              entity_id:
                - input_number.hp_shift_value_in_auto_mode_circuit2
        alias: Vorlauftemperatur zurücksetzen wenn Strom normal
mode: single
```

**Reply by TomHeckl** [reply]
Hi Basti,
Vielen Dank für das Beispiel.
Ich habe jetzt mal eine erste Automatisierung erstellt, die langsam absenkt und wieder langsam hochfährt, um zu intensive Heizvorgänge zu vermeiden. 
Mal sehen, ob das heute Abend so läuft.

```yaml
description: ""
triggers:
  - at: "21:00:00"
    trigger: time
  - at: "22:00:00"
    trigger: time
  - at: "00:00:00"
    trigger: time
  - at: "03:00:00"
    trigger: time
  - at: "04:00:00"
    trigger: time
  - at: "05:00:00"
    trigger: time
  - at: "06:00:00"
    trigger: time
  - at: "07:00:00"
    trigger: time
actions:
  - repeat:
      for_each:
        - input_number.hp_shift_value_in_auto_mode_circuit1
        - input_number.hp_shift_value_in_auto_mode_circuit2
      sequence:
        - data:
            entity_id: "{{ repeat.item }}"
            value: |-
              {% if now().hour == 21 %}
                -2
              {% elif now().hour == 22 %}
                -4
              {% elif now().hour == 0 %}
                -5
              {% elif now().hour == 3 %}
                -4
              {% elif now().hour == 4 %}
                -3
              {% elif now().hour == 5 %}
                -2
              {% elif now().hour == 6 %}
                -1
              {% elif now().hour == 7 %}
                0
              {% else %}
                {{ states(repeat.item) | float }}
              {% endif %}
          action: input_number.set_value
mode: single
```

VG
Tom

**Reply by basti242** [reply]
bin gespannt

**Comment by TomHeckl** [comment]
Meine Theorie wäre, dass ich die Werte für die Felder input_number ändere und dann die Automatisierung aus deiner yaml-Datei greift und die Änderungen an die WP überträgt.
Ist der Denkansatz richtig?
VG
Tom

**Reply by basti242** [reply]
Auf den ersten Blick würde ich sagen dass es gut aussieht.

**Reply by TomHeckl** [reply]
Bringt nicht das gewünschte Ergebnis. Muss input_number anpassen oder den Wert des sensors?
Irgendeine Automatisierung setzt den Wert von HK2 immer wieder auf 0 und ich denke, das kommt auch nicht bei der Wärmepumpe an. 
Mit modbus bin aber total überfragt ...

**Reply by TomHeckl** [reply]
HI Basti,
hast du eine Doku über die relevanten Register der Therma V?
Gibt es ein Tool, mit dem man das Setup mal außerhalb von Home Assistant testen kann?
Wäre super, wenn du mich da unterstützen könntest.
Danke und viele Grüße
Tom

**Reply by basti242** [reply]
schau mal hier: 

https://docs.google.com/spreadsheets/d/1nzYJzj6M_eGvW1HD7guehZE_RDtn0w31KEogzJ0uoaY/edit?gid=0#gid=0

**Comment by TomHeckl** [comment]
HI Basti,
erstmal vielen Dank für deine Geduld. :-)
Das Beschreiben der Register klappt einfach nicht. Auslesen ist kein Problem und wenn ich an der Anlage bei einem Kreis mit der Sollwertverschiebung auf "-2" gehe, wird das auch sofort in Home Assistant angezeigt. Wenn ich den Wert über Home Assistant schreiben will, reagiert die Anlage nicht. Auch wenn ich das direkt über die Entwicklerwerkzeuge / Aktionen versuche, keine Reaktion und keine Fehlermeldung im Protokoll. 
Bin mit meinem Latein irgendwie am Ende....
Hast du eine Idee? Wäre sehr sehr dankbar.
VG
Tom

**Reply by basti242** [reply]
Immer gern wenn es meine Zeit erlaubt.

Was genau hast du in das Entwicklerwerkzeug geschrieben? Zeig mal den Code.

**Reply by TomHeckl** [reply]
Sehr nett, von dir. :-)

Hier der Code:
```
action: modbus.write_register
data:
  hub: lg_heatpump
  address: 7
  slave: 1
  value: 0
```

**Reply by basti242** [reply]
Bei mir funktioniert das. Die Vorlauftemperatur von HK2 wird verschoben. 
Die Aktualisierung erfolgt ggf. mit Verzögerung, glaube bis zu 60 sec. Hast du mal ein bisschen gewartet?

**Reply by TomHeckl** [reply]
Sehr mysteriös, ja ich hab gewartet...

**Reply by TomHeckl** [reply]
Ich überlege gerade, ob ich mal das gesamte System neu starte, also Wärmepumpe, RS485toETH, Home Assistant...
Evtl. bringt das ja was...

**Reply by basti242** [reply]
bekommst du überhaupt irgendwelche Werte von der Pumpe? Temperaturen oder Ähnliches

**Reply by TomHeckl** [reply]
Ja, wie gesagt, das auslesen der Werte klappt, ganz gut...
![image](https://github.com/user-attachments/assets/30d1cda5-11c6-4554-b6c2-0c2223fb16f7)

**Reply by TomHeckl** [reply]
Hab jetzt auch mal versucht in das Register 40005 zu schreiben, aber auch das geht nicht. :-(
Wenn du noch eine Idee hast, wäre ich dankbar.

**Comment by basti242** [comment]
kannste mal schauen ob das geht
```yaml
action: modbus.write_coil
data:
  hub: lg_heatpump
  address: 2
  state: 0
  slave: 1
```
Das ist der silent mode.

Hast du viellleich noch eine test yaml für die Heizung die stört. Das hatte ich mal.
